name: 'on-approve'
description: 'Give the author a thumbs-up upon approving a PR'
branding:
  icon: 'thumbs-up'
  color: 'yellow'
author: 'rbarbazz'
inputs:
  repo-token:
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
