on: [pull_request_review]

jobs:
  approved_job:
    runs-on: ubuntu-latest
    name: on-approve
    steps:
      - uses: actions/checkout@v2
      - name: Approved action step
        uses: ./
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
